In [11]:
import seaborn as sns 
titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
titanic.shape

(891, 15)

In [13]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [14]:
manquants = titanic.isna().sum()
manquants[manquants > 0]

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

In [15]:
print(titanic["class"].value_counts())
print()
print(titanic["embark_town"].value_counts())
print()
pd_cross = titanic.groupby(["class", "embark_town"]).size().unstack()
pd_cross

class
Third     491
First     216
Second    184
Name: count, dtype: int64

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

/var/folders/p6/7tpgs9bx1y9bzkyrrllq_7cr0000gn/T/ipykernel_84238/2059766186.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pd_cross = titanic.groupby(["class", "embark_town"]).size().unstack()

embark_town  Cherbourg  Queenstown  Southampton
class
First               85           2          127
Second              17           3          164
Third               66          72          353